version: '3.8'
services:
  gateway:
    build: gateway/
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on: server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/
    container_name: server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:shareit
