CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    email varchar(512) NOT NULL,
    UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS item_requests (
                                             id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             description varchar(512) NOT NULL,
                                             requester_id bigint REFERENCES users (id),
                                             created_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items (
                                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar(100) NOT NULL,
                                     description varchar(512) NOT NULL,
                                     available varchar(50) NOT NULL,
                                     owner_id bigint REFERENCES users (id),
                                     item_request_id bigint REFERENCES item_requests (id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     start_date TIMESTAMP,
                                     end_date TIMESTAMP,
                                     booker_id bigint REFERENCES users (id),
                                     item_id bigint REFERENCES items (id),
                                     status varchar(100)
);

CREATE TABLE IF NOT EXISTS comments (
                                             id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             text varchar(512) NOT NULL,
                                             item_id bigint REFERENCES items (id),
                                             author_id bigint REFERENCES users (id),
                                             created_date TIMESTAMP
);